### ISSUE TITLE
Unable to create server process

### ISSUE THREAD

**Issue by hugo4715** [PlayPen/playpen-core#12]
> java.lang.RuntimeException: CreateProcessW() failed, error: 2
        at com.zaxxer.nuprocess.windows.WindowsProcess.start(WindowsProcess.java:251)
        at com.zaxxer.nuprocess.windows.WinProcessFactory.createProcess(WinProcessFactory.java:42)
        at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:240)
        at io.playpen.core.utils.process.XProcess.run(XProcess.java:67)
        at io.playpen.core.p3.step.ExecuteStep.runStep(ExecuteStep.java:97)
        at io.playpen.core.p3.PackageManager.execute(PackageManager.java:353)
        at io.playpen.core.coordinator.local.Local.provision(Local.java:595)
        at io.playpen.core.coordinator.local.Local.lambda$checkPackageForProvision$3(Local.java:1294)
        at java.lang.Thread.run(Unknown Source)

There is a problem when i try to provision a server but i have no idea on how i can fix this. I am using the client to send a provision request, the result is successful but the server process is unable to start.

**Comment by hugo4715** [comment]
The network, local and client are all running on a win10 machine.

**Comment by hugo4715** [comment]
Solved by upgrading nuprocess

**Comment by redxdev** [comment]
I'm glad you were able to solve it. Might I ask what version of nuprocess you upgraded to? Latest?

**Comment by redxdev** [comment]
Nevermind, I've upgraded the version used to 1.1.1. If you continue having this issue, let me know and I'll try to help troubleshoot it.

**Comment by hugo4715** [comment]
Yes i upgraded to 1.1.1 and it worked fine
